### ISSUE TITLE
Unnecessary double checking for thread safe singleton

### ISSUE THREAD

**Issue by fadi-botros** [eg-droid/Robust-Android-App#35]
https://github.com/ahmed-adel-said/Robust-Android-App/blob/e69ffd8a20bb927ae70a202b03b2014bc65158d3/datalayer/datasource/src/main/java/com/ahmedadel/robustandroid/datalayer/datasource/local/di/LocalComponentWrapper.kt#L28

Using `@Synchronized` (which is translated into Java's `synchronized` keyword) is enough I think. There is no need for double checking.

The double checking pattern is needed only (and it is broken) when trying to use `Atomic`s or to use the inner synchronized keyword (i.e. using the `synchronized` inside the if statement)

I'm not 100% sure of this, but there are some sources, like:
https://stackoverflow.com/questions/2482092/singleton-pattern-and-broken-double-checked-locking-in-a-real-world-java-applica

Also, in Kotlin, you can use the Singleton pattern using Kotlin new tools, like `by lazy`

**Comment by ahmedadeltito** [comment]
Thanks @fadi-botros for your comment.
But I think there is another problem here in this approach. The problem is I put the `@Synchronized` at the scope of the function since the `wrapper` reference can be not null in some cases so it doesn't make sense to be at the function scope. It makes more sense to be at the if condition scope of the `wrapper` checker. Did you get my point ?
